import { TestBed } from '@angular/core/testing';

import { UserService } from './user.service';
import {PublicUser, User} from '../interfaces/user';
import {Marios} from "../interfaces/marios";
import {HttpClient} from "@angular/common/http";
import {HttpTestingController} from "@angular/common/http/testing";

describe('UserService', () => {
  let service: UserService;
  let httpClientSpy: jasmine.SpyObj<HttpClient>;
  let httpTestingController: HttpTestingController;

  beforeEach(() => {
    TestBed.configureTestingModule({});
    service = TestBed.inject(UserService);
  });

  it('should be created', () => {
    expect(service).toBeTruthy();
  });
  // Generated by CodiumAI

  describe('UserService', () => {

    // Tests that removing element from public user list by UUID works as expected
    it('should remove element from public user list by UUID', () => {
      const userService = new UserService(httpClientSpy as any);
      const publicUsers: PublicUser[] = [{uuid: '1', userName: 'user1'}, {uuid: '2', userName: 'user2'}, {uuid: '3', userName: 'user3'}];
      const uuidToRemove = '2';
      const expectedPublicUsers: PublicUser[] = [{uuid: '1', userName: 'user1'}, {uuid: '3', userName: 'user3'}];
      const result = userService.removeElementFromPublicUserListByUUID(publicUsers, uuidToRemove);
      expect(result).toEqual(expectedPublicUsers);
    });
  });

});
